name: OrangeKillMessage
version: '${project.version}'
main: com.orangekillmessage.OrangeKillMessage
author: DuoDuoJuZi
website: https://github.com/duoduojuzi/OrangeKillMessage
description: 自定义你的击杀消息，伤害性不强，侮辱性极强
api-version: '1.20'
commands:
  okm:
    description: Main command
    aliases: km
  okmset:
    description: Set custom message
    aliases: kmset
  okmlist:
    description: List all custom message
    aliases: kmlist
permissions:
  okm:
    description: Main command
    default: true
